- name: installing something
  hosts: myserver
  become: yes
  tasks:
    - name: installing apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution=='ubuntu'
    - name: installing mysql
      apt:
        name: mysql-server
        state: present
      when: ansible_distribution=='ubuntu'
    - name: starting apache2
      service:
        name: apache2
        state: started
    - name: starting mysql
      service:
        name: mysql
        state: started
      when: ansible_distribution=='ubuntu'

    - name: installing php
      apt: name=php state=present
      when: ansible_distribution=='ubuntu'
    - name: installing php-fpm
      apt: name=php8.1-fpm state=present
      when: ansible_distribution=='ubuntu'
    - name: starting php-fpm
      service: name=php8.1-fpm state=started
      notify: ['restart nginx','restart mysql','restart php8.1-fpm']
      when: ansible_distribution=='ubuntu'

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
    - name: restart mysql
      service:
        name: mysql
        state: restarted
    - name: restart php8.1-fpm
      service:
        name: php8.1-fpm
        state: restarted
